### ISSUE TITLE
[BUG] - Sonarr - MKV not recognized, script deleting 

### ISSUE THREAD

**Issue by justinglock40** [RandomNinjaAtk/arr-scripts#138]
**Application**
SABnzbd

**Host platform**
Unraid

**Script**
Video.bash for SMA Processing 

**Script Version*
1.0.5

**Describe the bug**

2023-12-19 08:19:43 :: Video :: 1.0.5 :: SABnzbd Job: American Dad S19E22 1080p WEBRip x264-BAE
2023-12-19 08:19:43 :: Video :: 1.0.5 :: SABnzbd Category: sonarr
2023-12-19 08:19:43 :: Video :: 1.0.5 :: Script Versiion: 1.0.5
2023-12-19 08:19:43 :: Video :: 1.0.5 :: CONFIGURATION VERIFICATION
2023-12-19 08:19:43 :: Video :: 1.0.5 :: ##########################
2023-12-19 08:19:43 :: Video :: 1.0.5 :: Preferred Audio/Subtitle Languages: eng
2023-12-19 08:19:43 :: Video :: 1.0.5 :: Require Matching Language :: Disabled
2023-12-19 08:19:43 :: Video :: 1.0.5 :: Sickbeard MP4 Automator (SMA): ENABLED
2023-12-19 08:19:43 :: Video :: 1.0.5 :: Sickbeard MP4 Automator (SMA): Tagging: DISABLED
2023-12-19 08:19:43 :: Video :: 1.0.5 :: Processing 1 video files...
2023-12-19 08:19:43 :: Video :: 1.0.5 :: 1 of 1 :: Processing American Dad S19E22 1080p WEBRip x264-BAE.mkv
2023-12-19 08:19:43 :: Video :: 1.0.5 :: 1 of 1 :: 1 Audio Tracks Found!
2023-12-19 08:19:43 :: Video :: 1.0.5 :: 1 of 1 :: 1 Subtitle Tracks Found!
2023-12-19 08:19:43 :: Video :: 1.0.5 :: 1 of 1 :: Checking for preferred languages "eng"
2023-12-19 08:19:43 :: Video :: 1.0.5 :: 1 of 1 :: 1 "eng" Audio Tracks Found!
2023-12-19 08:19:43 :: Video :: 1.0.5 :: 1 of 1 :: 1 "eng" Subtitle Tracks Found!
2023-12-19 08:19:43 :: Video :: 1.0.5 :: 1 of 1 :: Processing complete for: American Dad S19E22 1080p WEBRip x264-BAE.mkv!
2023-12-19 08:19:43 :: Video :: 1.0.5 :: Processing 1 video files...
2023-12-19 08:19:43 :: Video :: 1.0.5 :: 1 of 1 :: Processing American Dad S19E22 1080p WEBRip x264-BAE.mkv
2023-12-19 08:19:43 :: Video :: 1.0.5 :: 1 of 1 :: Processing with SMA...
Manual processor started.
Python 64-bit 3.11.6 (main, Oct  4 2023, 06:22:18) [GCC 12.2.1 20220924].
Guessit version: 3.7.1.
/lsiopy/bin/python3
Loading config file /config/scripts/sma.ini.
Traceback (most recent call last):
  File "/config/scripts/sma/manual.py", line 519, in <module>
    main()
  File "/config/scripts/sma/manual.py", line 429, in main
    settings = ReadSettings(args['config'], logger=log)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/scripts/sma/resources/readsettings.py", line 474, in __init__
    self.readConfig(config)
  File "/config/scripts/sma/resources/readsettings.py", line 484, in readConfig
    self.threads = config.getint(section, 'threads')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/scripts/sma/resources/readsettings.py", line 89, in getint
    return super(SMAConfigParser, self).getint(section, option, vars=vars, fallback=fallback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/configparser.py", line 834, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/configparser.py", line 824, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/configparser.py", line 819, in _get
    return conv(self.get(section, option, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
2023-12-19 08:19:44 :: Video :: 1.0.5 :: 1 of 1 :: ERROR :: SMA Processing Error
2023-12-19 08:19:44 :: Video :: 1.0.5 :: INFO: deleted: American Dad S19E22 1080p WEBRip x264-BAE.mkv
2023-12-19 08:19:44 :: Video :: 1.0.5 :: ERROR: No video files found for processing

**To Reproduce**
Not sure what’s causing. I tried checking to make sure perms were the same for everything. 

**Expected behavior**
Copy video/audio and make new audio tracks for compatibility.

**Comment by RandomNinjaAtk** [comment]
This is likely caused by user error... Seems like you've broken your SMA config file... I suggest you delete it, restart the container, which should pull a new valid config.

If I had to guess what happened, you likely edited the file with a text editor that changed the line endings to a incompatible format.

The file I'm referring to is: https://github.com/RandomNinjaAtk/arr-scripts/blob/main/sabnzbd/sma.ini
