### ISSUE TITLE
[BUG] - Lidarr - Freya install

### ISSUE THREAD

**Issue by jasonpatrickellykrause** [RandomNinjaAtk/arr-scripts#174]
**Application**
 Lidarr

**Host platform**
Windows 11 23H2 (OS Build 22635.3139)

- Docker Desktop 4.71.1
- Ubuntu 22.04.3 LTS on WSL2

**Script**
lidarr/setup.bash

**Script Version**
version="1.1"

**Describe the bug**
After Lidarr container starts, I am seeing npm error downloading freya. (Full logs below)

```error
2024-02-03 12:42:55 npm ERR! code 128
2024-02-03 12:42:55 npm ERR! An unknown git error occurred
2024-02-03 12:42:55 npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/miraclx/freyr-js.git
2024-02-03 12:42:55 npm ERR! ssh -oStrictHostKeyChecking=accept-new: line 0: ssh: not found
2024-02-03 12:42:55 npm ERR! fatal: Could not read from remote repository.
2024-02-03 12:42:55 npm ERR! 
2024-02-03 12:42:55 npm ERR! Please make sure you have the correct access rights
2024-02-03 12:42:55 npm ERR! and the repository exists.
```

**To Reproduce**

1. Start container.

**Expected behavior**
Freya should install and script continues.

**Logs/Screenshots**

```log
2024-02-03 12:35:30 [custom-init] Files found, executing
2024-02-03 12:35:30 [custom-init] scripts_init.bash: executing...
2024-02-03 12:35:30   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2024-02-03 12:35:30                                  Dload  Upload   Total   Spent    Left  Speed
100  5307  100  5307    0     0  39333      0 --:--:-- --:--:-- --:--:-- 39604
2024-02-03 12:35:30 *** install packages ***
2024-02-03 12:35:30 fetch http://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
2024-02-03 12:35:30 fetch http://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
2024-02-03 12:35:31 OK: 619 MiB in 229 packages
2024-02-03 12:35:31 *** install freyr client ***
2024-02-03 12:35:31 fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
2024-02-03 12:35:31 fetch http://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
2024-02-03 12:35:31 fetch http://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
2024-02-03 12:35:31 OK: 619 MiB in 229 packages
2024-02-03 12:35:37 npm ERR! code 128
2024-02-03 12:35:37 npm ERR! An unknown git error occurred
2024-02-03 12:35:37 npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/miraclx/freyr-js.git
2024-02-03 12:35:37 npm ERR! ssh -oStrictHostKeyChecking=accept-new: line 0: ssh: not found
2024-02-03 12:35:37 npm ERR! fatal: Could not read from remote repository.
2024-02-03 12:35:37 npm ERR! 
2024-02-03 12:35:37 npm ERR! Please make sure you have the correct access rights
2024-02-03 12:35:37 npm ERR! and the repository exists.
2024-02-03 12:35:37 
2024-02-03 12:35:37 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-02-03T19_35_31_907Z-debug-0.log
```

```console
root@f9023254f52f:/# cat /root/.npm/_logs/2024-02-03T19_35_31_907Z-debug-0.log
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@9.6.6
2 info using node@v20.8.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/root/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:setEnvs Completed in 1ms
15 timing config:load Completed in 5ms
16 timing npm:load:configload Completed in 5ms
17 timing npm:load:mkdirpcache Completed in 0ms
18 timing npm:load:mkdirplogs Completed in 0ms
19 verbose title npm install miraclx/freyr-js
20 verbose argv "install" "--global" "miraclx/freyr-js"
21 timing npm:load:setTitle Completed in 1ms
22 timing config:load:flatten Completed in 1ms
23 timing npm:load:display Completed in 1ms
24 verbose logfile logs-max:10 dir:/root/.npm/_logs/2024-02-03T19_35_31_907Z-
25 verbose logfile /root/.npm/_logs/2024-02-03T19_35_31_907Z-debug-0.log
26 timing npm:load:logFile Completed in 5ms
27 timing npm:load:timers Completed in 0ms
28 timing npm:load:configScope Completed in 0ms
29 timing npm:load Completed in 13ms
30 timing config:load:flatten Completed in 0ms
31 timing arborist:ctor Completed in 0ms
32 silly logfile done cleaning log files
33 timing idealTree:init Completed in 6ms
34 timing idealTree Completed in 5023ms
35 timing command:install Completed in 5028ms
36 verbose stack Error: An unknown git error occurred
36 verbose stack     at makeError (/usr/lib/node_modules/npm/node_modules/@npmcli/git/lib/make-error.js:28:13)
36 verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/git/lib/spawn.js:37:26
36 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
37 verbose cwd /run/s6-rc:s6-rc-init:NfnKNm/servicedirs/s6rc-oneshot-runner
38 verbose Linux 5.15.146.1-microsoft-standard-WSL2
39 verbose node v20.8.1
40 verbose npm  v9.6.6
41 error code 128
42 error An unknown git error occurred
43 error command git --no-replace-objects ls-remote ssh://git@github.com/miraclx/freyr-js.git
44 error ssh -oStrictHostKeyChecking=accept-new: line 0: ssh: not found
44 error fatal: Could not read from remote repository.
44 error
44 error Please make sure you have the correct access rights
44 error and the repository exists.
45 verbose exit 128
46 timing npm Completed in 5131ms
47 verbose unfinished npm timer reify 1706988932008
48 verbose unfinished npm timer reify:loadTrees 1706988932012
49 verbose unfinished npm timer idealTree:userRequests 1706988932018
50 verbose code 128
51 error A complete log of this run can be found in: /root/.npm/_logs/2024-02-03T19_35_31_907Z-debug-0.log
```

**Additional context**
I am running lscr.io/linuxserver/lidarr:nightly

```yaml
  lidarr:
    image: 'lscr.io/linuxserver/lidarr:nightly'
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - '/mnt/d/data:/data'
      - 'lidarr-custom-cont-init:/custom-cont-init.d'
      - 'lidarr-custom-services:/custom-services.d'
      - 'lidarr:/config'
    ports:
      - '8686:8686'
    restart: unless-stopped
```

**Comment by RandomNinjaAtk** [comment]
Validated that it works in my configuration without issue, so it's not reproducible. Must be an issue somewhere on your side, which means there is nothing that can be done from this end, you must troubleshoot it yourself...
