### ISSUE TITLE
[BUG] - Lidarr-Extended Audio script- DEEMIX login

### ISSUE THREAD

**Issue by hockeygoalie35** [RandomNinjaAtk/arr-scripts#301]
Looks like possible issues with the way Deemix's login_via_arl function. Can anyone else confirm? To reproduce, run the Audio script and wait for a download attempt. An error like below should show. I've verified it on 2 instances....will investigate further. Confirmed on Audio script v2.48

![image](https://github.com/user-attachments/assets/21007e52-0b62-497c-9557-e726ab150546)

Full Traceback
```python
2024-08-25 17:59:06 :: Audio :: 2.48 :: 1 :: missing :: 2 of 3 :: Jinjer :: Someone's Daughter :: Single :: Download Attempt number 1
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/deemix", line 8, in <module>
    sys.exit(download())
             ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deemix/__main__.py", line 49, in download
    if not dz.login_via_arl(arl): arl = requestValidArl()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deezer/__init__.py", line 98, in login_via_arl
    user_data = self.gw.get_user_data()
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deezer/gw.py", line 72, in get_user_data
    return self.api_call('deezer.getUserData')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deezer/gw.py", line 48, in api_call
    ).json()
      ^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-08-25 17:59:10 :: Audio :: 2.48 :: 1 :: missing :: 2 of 3 :: Jinjer :: Someone's Daughter :: Single :: ERROR :: download failed, missing tracks...
```

**Comment by z00dev** [comment]
its probably the dependency on `py-deezer` whos  `login_via_arl` method seems borked. making any calls to dz.gw fail.

**Comment by hockeygoalie35** [comment]
You're right, my ARLChecker script works fine, which uses the requests library to manually interact with the API. I'm a little concerned however, as deezer stopped allowing new API applications roughly 6 months ago.

![image](https://github.com/user-attachments/assets/dde4b4e5-4162-41d5-a71a-954df9e28472)

**Comment by hockeygoalie35** [comment]
@z00dev  I've found the issue... All the Redhawk ARLs are down. Using a known good ARL works as expected. Closing issue.

**Comment by hockeygoalie35** [comment]
Closed as not related to lidarr-extended or downstream dependencies
