### ISSUE TITLE
[BUG] - Lidarr - parse error: Invalid numeric literal at line 2, column 0

### ISSUE THREAD

**Issue by Eric-sson** [RandomNinjaAtk/arr-scripts#45]
**Application**
Lidarr

**Script**
BeetsPostProcessor.bash
MetadataPostProcess.bash

**Script Version**
latest

**Describe the bug**
I am seeing the following error when running both scripts:

parse error: Invalid numeric literal at line 2, column 0

**To Reproduce**
1. Go to 'Artist'
2. Click on 'Preview Rename - Rename and Preview Retag - Retag'
3. Scroll down to 'System - Events'

**Expected behavior**
Not sure if the error has any impact.

**Comment by Eric-sson** [comment]
[BeetsPostProcessor.txt](https://github.com/RandomNinjaAtk/arr-scripts/files/12207294/BeetsPostProcessor.txt)

**Comment by RandomNinjaAtk** [comment]
So a bug fix that was just pushed may help. But it looks like you didn't follow the installation instructions because your missing required packages.

One thing to note, I'm currently not using those scripts because I've found they cause issues with Lidarr. You should also only have it trigger on import and upgrade, not retag.

Follow the installation instructions and the most recent changes should fix some of the errors your seeing. Keep in mind, it's untested...

**Comment by Eric-sson** [comment]
Which packages am I missing? 

I was hoping that the both scripts would also work for existing files therefore I ticked retag as well. But I guess this will only work for newly downloaded files?

**Comment by RandomNinjaAtk** [comment]
This may have been fixed with that last change, but I have not tested it. Both scripts are deprecated because they can tend to cause more issues with Lidarr than is desirable and I personally don't recommend you use them.

For discussions around the uses/challenges these scripts tried to solve, see these discussions: https://github.com/RandomNinjaAtk/arr-scripts/discussions/47

The scripts will remain in this repo, but no support will be provided going forward.

**Comment by wieluk** [comment]
Lidarr is still trying to start /config/extended/scripts/MetadataPostProcess.bash

```
2023-08-01 09:12:43.2|Error|EventAggregator|NotificationService failed while processing [TrackFileRetaggedEvent]

[v1.2.6.3313] System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/config/extended/scripts/MetadataPostProcess.bash' with working directory '/app/lidarr/bin'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at NzbDrone.Common.Processes.ProcessProvider.Start(String path, String args, StringDictionary environmentVariables, Action`1 onOutputDataReceived, Action`1 onErrorDataReceived) in ./Lidarr.Common/Processes/ProcessProvider.cs:line 189
   at NzbDrone.Common.Processes.ProcessProvider.StartAndCapture(String path, String args, StringDictionary environmentVariables) in ./Lidarr.Common/Processes/ProcessProvider.cs:line 229
   at NzbDrone.Core.Notifications.CustomScript.CustomScript.ExecuteScript(StringDictionary environmentVariables) in ./Lidarr.Core/Notifications/CustomScript/CustomScript.cs:line 308
   at NzbDrone.Core.Notifications.CustomScript.CustomScript.OnTrackRetag(TrackRetagMessage message) in ./Lidarr.Core/Notifications/CustomScript/CustomScript.cs:line 141
   at NzbDrone.Core.Notifications.NotificationService.Handle(TrackFileRetaggedEvent message) in ./Lidarr.Core/Notifications/NotificationService.cs:line 354
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)
```

Why is this happening?

**Comment by RandomNinjaAtk** [comment]
@wieluk You’re on your own, read the previous comment for details

**Comment by wieluk** [comment]
Oh I see where it came from. The autoconfig added the metadata post process connection thanks anyway.

**Comment by RandomNinjaAtk** [comment]
@wieluk Yeah, that is true, when these first scripts came out it added them… However, AutoConfig no longer does that, but there isn’t an easy way to reverse it, if you already had them added. So if you remove them, they shouldn’t be re-added as long as your on the latest scripts updates…
